/*package com.peakokk.domain;

*//**
 * User generated by hbm2java
 *//*
 
 public enum UserTypeEnum
{
	ADMIN("Admin"), CHEF("Chef"), USER("User");
	String user_type;
	
	UserTypeEnum(String user_type)
	{
		this.user_type=user_type;
	}
	public String toString() 
	{
    	return user_type;
   	}
}
 
 */
 