package com.peakokk.domain;


/**
 * User generated by hbm2java
 */

public class Usertype  implements java.io.Serializable 
{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer userTypeId;
	
	private String userType;
	
	public Usertype() {
	}
		
	public Integer getUserTypeId() {
        return this.userTypeId;
    }
    
    public void setUserTypeId(Integer userTypeId) {
        this.userTypeId = userTypeId;
    }
    
    
    
    public String getUserType() {
		return userType;
	}
    
    public void setUserType(String userType) {
		this.userType = userType;
	}
   /* public void setUserTypeId(String userType) {
        this.userType = userType;
    }
    public String toString() {
        return userType.toString();
    }*/
}