package com.peakokk.domain;

/**
 * User generated by hbm2java
 */

public class User implements java.io.Serializable
{

    /**
	 * 
	 */
    private static final long serialVersionUID = 1L;

    private Integer userId;

    private String username;
    private String emailId;
    private String password;
    private String firstName;
    private String middleName;
    private String lastName;
    private Integer birthDate;
    private Integer birthMonth;
    private Integer birthYear;
    private Integer userTypeId;
    private Character gender;
    private String confirmPassword;
    private Boolean termsCheckbox;
    private String contactNumber;

    public User()
    {
    }

    public User(String username, String emailId, String password, String firstName, String middleName, String lastName,
            Integer birthDate, Integer birthMonth, Integer birthYear, Integer userTypeId, Character gender,
            String confirmPassword, Boolean termsCheckbox, String contactNumber)
    {
        this.username = username;
        this.emailId = emailId;
        this.password = password;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.birthDate = birthDate;
        this.birthMonth = birthMonth;
        this.birthYear = birthYear;
        this.userTypeId = userTypeId;
        this.gender = gender;
        this.confirmPassword = confirmPassword;
        this.termsCheckbox=termsCheckbox;
        this.contactNumber= contactNumber;
    }

    public Integer getUserId()
    {
        return this.userId;
    }

    public void setUserId(Integer userId)
    {
        this.userId = userId;
    }

    public String getUsername()
    {
        return username;
    }

    public void setUsername(String username)
    {
        this.username = username;
    }

    public String getEmailId()
    {
        return this.emailId;
    }

    public void setEmailId(String emailId)
    {
        this.emailId = emailId;
    }

    public String getPassword()
    {
        return this.password;
    }

    public void setPassword(String password)
    {
        this.password = password;
    }

    public String getFirstName()
    {
        return this.firstName;
    }

    public void setFirstName(String firstName)
    {
        this.firstName = firstName;
    }

    public String getMiddleName()
    {
        return this.middleName;
    }

    public void setMiddleName(String middleName)
    {
        this.middleName = middleName;
    }

    public String getLastName()
    {
        return this.lastName;
    }

    public void setLastName(String lastName)
    {
        this.lastName = lastName;
    }

    public Integer getBirthDate()
    {
        return this.birthDate;
    }

    public void setBirthDate(Integer birthDate)
    {
        this.birthDate = birthDate;
    }

    public Integer getBirthMonth()
    {
        return this.birthMonth;
    }

    public void setBirthMonth(Integer birthMonth)
    {
        this.birthMonth = birthMonth;
    }

    public Integer getBirthYear()
    {
        return this.birthYear;
    }

    public void setBirthYear(Integer birthYear)
    {
        this.birthYear = birthYear;
    }

    public Integer getUserTypeId()
    {
        return this.userTypeId;
    }

    public void setUserTypeId(Integer userTypeId)
    {
        this.userTypeId = userTypeId;
    }

    public Character getGender()
    {
        return this.gender;
    }

    public void setGender(Character gender)
    {
        this.gender = gender;
    }

    public String getConfirmPassword()
    {
        return confirmPassword;
    }

    public void setConfirmPassword(String confirmPassword)
    {
        this.confirmPassword = confirmPassword;
    }

    public Boolean getTermsCheckbox()
    {
        return termsCheckbox;
    }

    public void setTermsCheckbox(Boolean termsCheckbox)
    {
        this.termsCheckbox = termsCheckbox;
    }

    public String getContactNumber()
    {
        return contactNumber;
    }

    public void setContactNumber(String contactNumber)
    {
        this.contactNumber = contactNumber;
    }

}
